### ISSUE TITLE
Request for updated AEG app support

### ISSUE THREAD

**Issue by HenDog273** [davidjbradshaw/homebridge-aeg-wellbeing#7]
**Is your feature request related to a problem? Please describe:**

Hey! The AEG Wellbeing app has migrated over to the AEG app. Is there anyway to update this plugin? Thank you!

**Describe the solution you'd like:**
 Updated plugin to support new app

**Describe alternatives you've considered:**

**Additional context:**

**Comment by davidjbradshaw** [comment]
Do the two apps uses the same API?

Either it will just work, or it will need an entire new plugin.

**Comment by HenDog273** [comment]
Hey thanks for the response. Not 100% sure, it appears to have the same API as the wellbeing app. I think its my bad as I have an AEG AC unit rather than a purifier, so not sure if it's supported on this plugin?

**Comment by davidjbradshaw** [comment]
I have no way of testing it, but I expect it would be a different device type in HomeKit. 

If you want to give it a go and it uses the same API, then I expect this codebase would get you 80% of the way there.
