### ISSUE TITLE
AEG blocked token URL

### ISSUE THREAD

**Issue by AlanSmithe** [davidjbradshaw/homebridge-aeg-wellbeing#9]
When I directly go to the URL I get the error:
curl "https://electrolux-wellbeing-client.vercel.app/api/mu52m5PR9X"
Payment required
DEPLOYMENT_DISABLED

I see the IOS app now uses two different URL's
    https://ws.eu.ocp.electrolux.one
    https://api.eu.ocp.electrolux.one

**Comment by davidjbradshaw** [comment]
Are you able to make a patch for this new url?

**Comment by tomekkleszcz** [comment]
Hi, I've tried to use this plugin, however I faced the same issue as @AlanSmithe . I don't want to advertise in any way, but I've  created a new plugin: https://github.com/tomekkleszcz/homebridge-electrolux-devices to connect my Comfort 600 AC, and Well A7 air purifier to Homekit. It uses these 2 URL's you've mentioned, so if you would like to try out my plugin I'll be more than happy.

@davidjbradshaw If you are still interested in maintaining this library, I think we could work together to create a patch and add support other devices based on the code I wrote.

**Comment by AlanSmithe** [comment]
wow nice, that was quick. Did Electrolux release api documentation or did you reverse engineer the IOS/Android app?

**Comment by tomekkleszcz** [comment]
> wow nice, that was quick. Did Electrolux release api documentation or did you reverse engineer the IOS/Android app?

I've reverse engineered it.

**Comment by davidjbradshaw** [comment]
@tomekkleszcz my health isn’t great, so I can do much right now. I’m happy to either give you access to everything or hand it over to you.

**Comment by davidjbradshaw** [comment]
Alternatively if you have a whole new plugin for the new API, maybe the best solution is just to update this to point to your project? Add something to the HomePage and the log output for this project pointing users to your stuff. 

If you want to do that, I’m happy to take a PR and publish it.
